### ISSUE TITLE
关于结构体Clinet字段没有导出的疑惑

### ISSUE THREAD

**Issue by lakevilladom** [zhshch2002/goreq#4]
```go
type Client struct {
	cli        *http.Client
	middleware []Middleware
	handler    Handler
}
```
为什么这里面字段都是不可导出的，这是不是意味着普通用户没有权限个性化设置http.Client

**Comment by zhshch2002** [comment]
设计上不希望用户直接修改这些字段。个性化设置Client是通过中间件的方式实现。使用`func (s *Client) Use(m ...Middleware)`添加中间件，在中间件中实现拦截或者加工请求、响应来实现开发。

**Comment by lakevilladom** [comment]
那类似与于以前goribot中的AddCookieToJar这种功能只能这个库自己实现这个方法，我们不能通过中间件实现？
我尝试了，没有成功，因为压根就访问不到Client
